set_datetime:
  name: Set Date and Time
  description: Set SAJ R5 Inverter Date and Time
  target:
    entity:
      integration: saj_modbus
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: saj_modbus
    datetime:
      required: false
      example: "2025-04-19T12:34:56"
      selector:
        datetime:
